name:                robotone
version:             0.1.0.0
github:              "daniel-manning/robotone"
license:             custom
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/daniel-manning/robotone#readme>

dependencies:
- base >= 4.7 && < 5


library:
  source-dirs: src
  dependencies:
    - containers
    - mtl
    - parsec
    - logict
    - QuickCheck
    - transformers

executables:
  robotone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - robotone
    - containers
    - mtl
    - logict
    - transformers

tests:
  robotone-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - robotone
    - hspec
    - QuickCheck
